version: '3'

services:
  gympoint-backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - gympoint-redis
      - gympoint-mongo
      - gympoint-postgres
    image: gympoint-backend
    container_name: gympoint-backend
    restart: unless-stopped
    env_file: .env
    environment:
      - APP_URL=$APP_URL
      - NODE_ENV=$NODE_ENV
      - PORT=$PORT
      - APP_SECRET=$APP_SECRET
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - MAIL_HOST=$MAIL_HOST
      - MAIL_PORT=$MAIL_PORT
      - MAIL_USER=$MAIL_USER
      - MAIL_PASS=$MAIL_PASS
      - SENTRY_DSN=$SENTRY_DSN

    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - gympoint-network

  gympoint-redis:
    image: redis
    container_name: gympoint-redis
    networks:
      - gympoint-network

  gympoint-postgres:
    image: postgres:11.2-alpine
    container_name: gympoint-postgres
    env_file: .env
    environment:
      - POSTGRES_DB=$DB_PASS
      - POSTGRES_PASSWORD=$DB_NAME

  gympoint-mongo:
    image: mongo:4.1.8-xenial
    container_name: gympoint-mongo
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - gympoint-network

networks:
  gympoint-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
